"""Tests for data models."""

from datetime import datetime

from ytarchive.models import ArchiveManifest, Caption, Video, VideoSnippet, VideoStatistics


def test_video_snippet():
    """Test VideoSnippet model."""
    data = {
        "publishedAt": "2024-01-01T00:00:00Z",
        "channelId": "UC123",
        "title": "Test Video",
        "description": "Test description",
        "thumbnails": {},
        "channelTitle": "Test Channel",
        "categoryId": "22",
    }
    snippet = VideoSnippet(**data)
    assert snippet.title == "Test Video"
    assert snippet.channel_id == "UC123"


def test_video_statistics():
    """Test VideoStatistics model."""
    data = {
        "viewCount": "1000",
        "likeCount": "50",
    }
    stats = VideoStatistics(**data)
    assert stats.view_count == 1000
    assert stats.like_count == 50


def test_video_model():
    """Test complete Video model."""
    data = {
        "id": "test123",
        "snippet": {
            "publishedAt": "2024-01-01T00:00:00Z",
            "channelId": "UC123",
            "title": "Test Video",
            "description": "Test",
            "thumbnails": {},
            "channelTitle": "Test Channel",
            "categoryId": "22",
        },
        "statistics": {
            "viewCount": "1000",
        },
    }
    video = Video(**data)
    assert video.id == "test123"
    assert video.snippet.title == "Test Video"
    assert video.statistics.view_count == 1000


def test_caption_model():
    """Test Caption model."""
    data = {
        "id": "cap123",
        "language": "en",
        "name": "English",
        "isAutoGenerated": False,
    }
    caption = Caption(**data)
    assert caption.language == "en"
    assert not caption.is_auto_generated


def test_archive_manifest():
    """Test ArchiveManifest model."""
    manifest = ArchiveManifest(
        video_id="test123",
        title="Test Video",
        archived_at=datetime.now(),
        metadata_file="/path/to/metadata.json",
    )
    assert manifest.video_id == "test123"
    assert manifest.caption_files == {}
