"""Data models for YouTube API responses."""

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class VideoSnippet(BaseModel):
    """Video snippet metadata."""

    published_at: datetime = Field(alias="publishedAt")
    channel_id: str = Field(alias="channelId")
    title: str
    description: str
    thumbnails: dict[str, Any]
    channel_title: str = Field(alias="channelTitle")
    tags: list[str] = Field(default_factory=list)
    category_id: str = Field(alias="categoryId")
    default_language: str | None = Field(default=None, alias="defaultLanguage")
    default_audio_language: str | None = Field(default=None, alias="defaultAudioLanguage")


class VideoStatistics(BaseModel):
    """Video statistics."""

    view_count: int = Field(alias="viewCount")
    like_count: int | None = Field(default=None, alias="likeCount")
    comment_count: int | None = Field(default=None, alias="commentCount")


class VideoContentDetails(BaseModel):
    """Video content details."""

    duration: str
    dimension: str
    definition: str
    caption: str
    licensed_content: bool = Field(alias="licensedContent")


class Video(BaseModel):
    """Complete video metadata."""

    model_config = {"populate_by_name": True}

    id: str
    snippet: VideoSnippet
    statistics: VideoStatistics | None = None
    content_details: VideoContentDetails | None = Field(default=None, alias="contentDetails")


class Caption(BaseModel):
    """Caption track metadata."""

    model_config = {"populate_by_name": True}

    id: str
    language: str
    name: str
    is_auto_generated: bool = Field(alias="isAutoGenerated")


class ArchiveManifest(BaseModel):
    """Manifest of archived video with local file paths."""

    video_id: str
    title: str
    archived_at: datetime
    video_file: str | None = None
    metadata_file: str
    thumbnail_file: str | None = None
    caption_files: dict[str, str] = Field(default_factory=dict)  # lang -> file path
